
node {
    try {
         stage("checkout")
         {
           checkout scm
         }
        
        dir('.\\javascript'){
        stage('Install Dependencies') {
            // Install npm dependencies
            bat 'npm install'
        }
        
        stage('Run Node Script') {
             withCredentials([string(credentialsId: 'git-pat', variable: 'GITHUB_TOKEN')]) {
             bat """
                    set GITHUB_TOKEN=%GITHUB_TOKEN%
                    node index.js AyushGhagre direct_member FrontEnd
                    """
            }
            
        }
        }
    } catch (Exception e) {
        currentBuild.result = 'FAILURE'
        echo "Encountered the exception"
    } 
}

